# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 15:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('date_start', models.DateTimeField()),
                ('date_duration', models.DurationField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('attenders_num', models.IntegerField(default=0)),
                ('attenders', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
                ('invited', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
                ('private', models.BooleanField()),
            ],
        ),
    ]
