# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-16 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
