# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_calendar', '0009_auto_20160818_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
